### ISSUE TITLE
copies files from watch_dir to work_dir then does nothing (running on docker)

### ISSUE THREAD

**Issue by DSew20** [ThePornDatabase/namer#196]
Hello,

I've set up namer on docker, using the docker_compose.  I'm passing the 4 folders as per the compose file below.  Namer moved the files from 'watch' to 'work', but then seems to have stopped.  I've added the porndb_token, added uid / gid as per the compose file.

I have also enabled the web-server (web = True), but not sure how to access this to view if working.

Any ideas how to move forward with this?

DOCKER COMPOSE:
```
version: "3"
services:
  namer:
    container_name: namer
    image: ghcr.io/theporndatabase/namer:latest
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=Europe/London
      - NAMER_CONFIG=/config/namer.cfg
    volumes:
      #- /apps/namer/:/config <- this will store the namer.cfg file copied by you from the git repo ( namer/namer.cfg.default )
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxx/Config/namer:/config

      - /media:/data #<- this will have the four folders namer needs to work, referenced in the namer.cfg file you create.

      - /srv/dev-disk-by-uuid-xxxxxxxxxxxx/downloads:/data/watch_dir
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxx/_work:/data/work_dir
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxx/_failed:/data/failed_dir
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxx/z_:/data/dest_dir
      
    restart: always
```

The config is thus:

```
new_relative_path_name={full_site}/{full_site} - {date} - {name} [WEBDL-{resolution}].{ext}

# directory where new downloads go.
watch_dir = data/watch_dir

# temporary directory where work is done.
# a log file shows attempted matches and match closeness.
work_dir = data/work_dir

# Should processing fail the file or directory is moved here.
# retries occur every 12 hours.   Files can be manually moved to watch-dir
# to force reprocessing.
failed_dir = data/failed_dir

# dir where finalized files get written.
dest_dir = data/dest_dir
```
